/**
 * gen-shl.ts (bun) — package the longitudinal example Bundle as a SMART Health
 * Link: encrypt it (compact JWE, dir/A256GCM) and emit the committed artifacts
 * the viewer and docs consume. Direct-file mode (flag "U").
 *
 *   input/images/viewer/example.jwe   the ciphertext (published static asset)
 *   input/images/viewer/shl.json      the viewer's default link (relative url)
 *   input/images/viewer/shlink.txt    canonical shlink:/ for the published site
 *   input/images/viewer/_shlink-local-ig.txt  shlink:/ for localhost:5525 testing
 *                                            (underscore -> not published)
 *
 * Run ahead of the publisher:  bun scripts/gen-shl.ts
 */
import { encryptCompact, b64uFromBytes, bytesFromB64u } from "../viewer-src/jwe.mjs";

// The canonical viewer is the one the IG itself publishes (the auto IG builder
// serves our JS viewer). Both the viewer and the encrypted file live under the
// IG's /viewer/ path, so the demo is same-origin. A full shareable link is
// <viewer>/index.html#shlink:/<payload>.
const VIEWER_BASE = "https://build.fhir.org/ig/jmandel/periodicity/viewer";
const LABEL = "Periodicity — synthetic longitudinal period-tracking export";
const dir = `${import.meta.dir}/../input/images/viewer`;
const root = `${import.meta.dir}/..`;

// FIXED public demo key + IV: this is synthetic data meant to be openable by
// anyone, and pinning them makes example.jwe / shl.json / shlink.txt byte-stable
// across builds (no churn) so the link can be documented on the examples page.
// NEVER reuse a fixed key/IV for real patient data — gen a fresh random key+IV.
const keyB64 = "-iXXJ2n57QEfYcKZPqjzvde4Y_XaBdqjzmRUvRhwVcI";
const ivB64 = "wrcwWOZXCZuO6fMQ";
const key = bytesFromB64u(keyB64);

const bundle = await Bun.file(`${root}/input/resources/Bundle-period-tracking-longitudinal-example.json`).text();

const jwe = await encryptCompact(bundle, key, { iv: bytesFromB64u(ivB64) });
await Bun.write(`${dir}/example.jwe`, jwe);

const enc = new TextEncoder();
const shlinkPayload = (fileUrl: string) => "shlink:/" + b64uFromBytes(enc.encode(JSON.stringify({ url: fileUrl, key: keyB64, flag: "U", label: LABEL, v: 1 })));
const share = (viewer: string, file: string) => `${viewer}#${shlinkPayload(file)}`;

// viewer default: relative url so the same shl.json works at any base
await Bun.write(`${dir}/shl.json`, JSON.stringify({ url: "example.jwe", key: keyB64, flag: "U", label: LABEL, v: 1 }, null, 2));
// canonical shareable link (IG-published viewer + IG-hosted encrypted file)
await Bun.write(`${dir}/shlink.txt`, share(`${VIEWER_BASE}/index.html`, `${VIEWER_BASE}/example.jwe`) + "\n");
// local test links (underscore -> not published by the IG Publisher)
await Bun.write(`${dir}/_shlink-local-ig.txt`, share("http://localhost:5525/viewer/index.html", "http://localhost:5525/viewer/example.jwe") + "\n");

// Inject the live shareable link into the examples page (between markers), so the
// published spec shows the exact shlink:/ that wraps the example Bundle.
const shareUrl = share(`${VIEWER_BASE}/index.html`, `${VIEWER_BASE}/example.jwe`);
const examplesPath = `${root}/input/pagecontent/examples.md`;
let md = await Bun.file(examplesPath).text();
const block = [
  "<!-- SHLINK:START (generated by scripts/gen-shl.ts — do not edit by hand) -->",
  `[**▶ Open the longitudinal example in the clinician viewer**](${shareUrl}){:target="_blank" rel="noopener"}`,
  "",
  "The shareable SMART Health Link (viewer-prefixed `shlink:/…`) — copy it, or open it on any device:",
  "",
  "```",
  shareUrl,
  "```",
  "<!-- SHLINK:END -->",
].join("\n");
const re = /<!-- SHLINK:START[\s\S]*?<!-- SHLINK:END -->/;
if (re.test(md)) { md = md.replace(re, block); await Bun.write(examplesPath, md); console.log("  updated examples.md SHLINK block"); }
else console.log("  (no SHLINK markers in examples.md; skipped injection)");

console.log(`wrote example.jwe (${jwe.length} chars), shl.json, shlink.txt (+ local test links)`);
console.log(`  key=${keyB64.slice(0, 10)}… (fixed public demo key)`);
