/** Shared Cycle narrative renderer; callback-free in its portable mode. */
import type { CycleContentRenderer } from './renderer';
import { renderLiquid as renderLiquidTemplate } from './liquid';
import { renderResourceFragment } from '../fhir/fragments';

export function missingIncludePlaceholder(name: string): string {
  return `<div class="ig-editor-missing-include" style="border:1px dashed #b58900;background:#fff8e1;color:#7a5c00;padding:6px 10px;border-radius:4px;font-size:12px;margin:8px 0">Include <code>${name}</code> is generated by the site's build wrapper and isn't part of the IG source — not shown in this preview.</div>`;
}

/**
 * Construct the standard Cycle content policy over a closed semantic SiteBuild.
 * Includes, generated fragments, resource fragments, and site data are all
 * resolved from the request's immutable context. No compiler, native template,
 * filesystem or ambient active service is consulted.
 */
export function createCycleContentRenderer(): CycleContentRenderer {
  return {
    renderLiquid(source, request) {
      const context = request.context;
      try {
        return renderLiquidTemplate(source, {
          includes: context.includes,
          ig: context.ig,
          siteData: context.siteData,
          assetInclude: (name) => context.generatedFragment(name)
            ?? context.textAsset(name)
            ?? (name === 'sample-viewer-links.md' ? missingIncludePlaceholder(name) : null),
          fragment: (args) => renderResourceFragment(
            args,
            context.resolveFragmentResource,
            { fhirVersion: context.fhirVersion },
          ),
        });
      } catch (error: any) {
        throw new Error(`Liquid failed for ${request.slug}.md: ${error.message}`);
      }
    },
  };
}
